name: Semantic Bump

on:
  push:
    branches:
      - master

jobs:
  bump:
    if: github.repository_owner == 'Kapiche'
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.7.0
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/exec
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_EMAIL: bot@kapiche.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo new release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
