name: Semantic Bump

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  bump:
    if: github.repository_owner == 'Kapiche'
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v2.7.0
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/exec
            @semantic-release/npm
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_EMAIL: bot@kapiche.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Echo new release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
