name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Code Review
        uses: step-security/ai-codewise@e352b2a5372e83d61ad449550deb2f3c61089e09 # v1.0.0

  lint:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    needs: dependency-scan
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          registry.npmjs.org:443

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set shell options
      run: |
        set -o xtrace

    - name: Install dependencies
      run: |
        node -v
        npm ci --no-optional

    - name: Run linter
      run: |
        npm run lint

    - name: Upload eslint report
      uses: github/codeql-action/upload-sarif@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v1
      with:
        sarif_file: results.sarif

  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    needs: dependency-scan
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            metrics.semgrep.dev:443
            semgrep.dev:443
            api.snapcraft.io:443

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v2
      - uses: returntocorp/semgrep-action@5f527831fb11fa698f72b1181080d95a04755a2a # v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}

  analyze:
    permissions:
      actions: read # for github/codeql-action/init to get workflow details
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/analyze to upload SARIF results
    name: Analyze
    runs-on: ubuntu-latest
    needs: dependency-scan
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          registry.npmjs.org:443
          uploads.github.com:443
          objects.githubusercontent.com:443

    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    - name: Install dependencies
      run: |
        node -v
        npm ci --no-optional

    - name: Run a build
      run: |
        npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@1813ca74c3faaa3a2da2070b9b8a0b3e7373a0d8 # v1

  dependency-scan:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          ghcr.io:443
          pkg-containers.githubusercontent.com:443

    - name: Checkout the code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v2
      with:
        fetch-depth: 0

    - name: Run vulnerability scanner in repo mode
      if: github.actor != 'dependabot[bot]'
      uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # 0.2.1
      with:
        scan-type: 'fs'
        ignore-unfixed: false
        exit-code: 1
        format: 'table'
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH'
        security-checks: 'vuln,config,secret'

    - name: Run vulnerability scanner in repo mode
      if: github.actor == 'dependabot[bot]'
      uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # 0.2.1
      with:
        scan-type: 'fs'
        ignore-unfixed: false
        exit-code: 1
        format: 'table'
        vuln-type: 'library'
        severity: 'MEDIUM,HIGH,CRITICAL'
        security-checks: 'vuln,config,secret'
